joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 4    #controller input number for x axis of bot(right stick vertical)
    scale_linear:
      x: 0.5    #normal speed
    scale_linear_turbo:
      x: 1.0    #turbo speed

    axis_angular:
      yaw: 3    #controller input number for yaw(right stick horiz)
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0


    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true